<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="7.0.20" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.14.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\API.Application.DTO\API.Application.DTO.csproj" />
    <ProjectReference Include="..\API.Application.Interface\API.Application.Interface.csproj" />
    <ProjectReference Include="..\API.Domain.Interface\API.Domain.Interface.csproj" />
  </ItemGroup>

</Project>
